[tool.poetry]
name = "lightning7-ssl"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "lightning7_ssl"}]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.5"
protobuf = "^4.21.11"
protobuf-to-dict = {git = "ssh://git@github.com/wearefair/protobuf-to-dict"}


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
