"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import grsim_commands_pb2
import grsim_replacement_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class grSim_Packet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMMANDS_FIELD_NUMBER: builtins.int
    REPLACEMENT_FIELD_NUMBER: builtins.int
    @property
    def commands(self) -> grsim_commands_pb2.grSim_Commands: ...
    @property
    def replacement(self) -> grsim_replacement_pb2.grSim_Replacement: ...
    def __init__(
        self,
        *,
        commands: grsim_commands_pb2.grSim_Commands | None = ...,
        replacement: grsim_replacement_pb2.grSim_Replacement | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["commands", b"commands", "replacement", b"replacement"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["commands", b"commands", "replacement", b"replacement"]
    ) -> None: ...

global___grSim_Packet = grSim_Packet
