"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class UidEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HASH_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    hash: builtins.str
    flags: builtins.int
    def __init__(
        self,
        *,
        hash: builtins.str | None = ...,
        flags: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["flags", b"flags", "hash", b"hash"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["flags", b"flags", "hash", b"hash"]) -> None: ...

global___UidEntry = UidEntry

@typing_extensions.final
class Uid(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTS_FIELD_NUMBER: builtins.int
    @property
    def parts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UidEntry]: ...
    def __init__(
        self,
        *,
        parts: collections.abc.Iterable[global___UidEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["parts", b"parts"]) -> None: ...

global___Uid = Uid

@typing_extensions.final
class LogRequest(google.protobuf.message.Message):
    """This message can be modified to describe arbitraty log locations,
    for example logs that can be downloaded from our NAS or
    that are offered peer-to-peer.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str
    def __init__(
        self,
        *,
        path: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["path", b"path"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["path", b"path"]) -> None: ...

global___LogRequest = LogRequest

@typing_extensions.final
class LogOfferEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _QUALITY:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _QUALITYEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LogOfferEntry._QUALITY.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PERFECT: LogOfferEntry._QUALITY.ValueType  # 1
        UNKNOWN: LogOfferEntry._QUALITY.ValueType  # 2
        UNREADABLE: LogOfferEntry._QUALITY.ValueType  # 3

    class QUALITY(_QUALITY, metaclass=_QUALITYEnumTypeWrapper): ...
    PERFECT: LogOfferEntry.QUALITY.ValueType  # 1
    UNKNOWN: LogOfferEntry.QUALITY.ValueType  # 2
    UNREADABLE: LogOfferEntry.QUALITY.ValueType  # 3

    NAME_FIELD_NUMBER: builtins.int
    QUALITY_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    name: builtins.str
    quality: global___LogOfferEntry.QUALITY.ValueType
    @property
    def uri(self) -> global___LogRequest: ...
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        quality: global___LogOfferEntry.QUALITY.ValueType | None = ...,
        uri: global___LogRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name", b"name", "quality", b"quality", "uri", b"uri"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "quality", b"quality", "uri", b"uri"]) -> None: ...

global___LogOfferEntry = LogOfferEntry

@typing_extensions.final
class LogOffer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LogOfferEntry]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___LogOfferEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___LogOffer = LogOffer
