"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _InputSourceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _InputSourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_InputSourceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AllSamplers: _InputSourceType.ValueType  # 1
    StandardSampler: _InputSourceType.ValueType  # 2
    EndInObstacleSampler: _InputSourceType.ValueType  # 3
    EscapeObstacleSampler: _InputSourceType.ValueType  # 4

class InputSourceType(_InputSourceType, metaclass=_InputSourceTypeEnumTypeWrapper): ...

AllSamplers: InputSourceType.ValueType  # 1
StandardSampler: InputSourceType.ValueType  # 2
EndInObstacleSampler: InputSourceType.ValueType  # 3
EscapeObstacleSampler: InputSourceType.ValueType  # 4
global___InputSourceType = InputSourceType

@typing_extensions.final
class Vector(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float | None = ...,
        y: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["x", b"x", "y", b"y"]) -> None: ...

global___Vector = Vector

@typing_extensions.final
class CircleObstacle(google.protobuf.message.Message):
    """static obstacles"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CENTER_FIELD_NUMBER: builtins.int
    @property
    def center(self) -> global___Vector: ...
    def __init__(
        self,
        *,
        center: global___Vector | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["center", b"center"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["center", b"center"]) -> None: ...

global___CircleObstacle = CircleObstacle

@typing_extensions.final
class RectObstacle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOTTOM_LEFT_FIELD_NUMBER: builtins.int
    TOP_RIGHT_FIELD_NUMBER: builtins.int
    @property
    def bottom_left(self) -> global___Vector: ...
    @property
    def top_right(self) -> global___Vector: ...
    def __init__(
        self,
        *,
        bottom_left: global___Vector | None = ...,
        top_right: global___Vector | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bottom_left", b"bottom_left", "top_right", b"top_right"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bottom_left", b"bottom_left", "top_right", b"top_right"]) -> None: ...

global___RectObstacle = RectObstacle

@typing_extensions.final
class TriangleObstacle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    P1_FIELD_NUMBER: builtins.int
    P2_FIELD_NUMBER: builtins.int
    P3_FIELD_NUMBER: builtins.int
    @property
    def p1(self) -> global___Vector: ...
    @property
    def p2(self) -> global___Vector: ...
    @property
    def p3(self) -> global___Vector: ...
    def __init__(
        self,
        *,
        p1: global___Vector | None = ...,
        p2: global___Vector | None = ...,
        p3: global___Vector | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["p1", b"p1", "p2", b"p2", "p3", b"p3"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["p1", b"p1", "p2", b"p2", "p3", b"p3"]) -> None: ...

global___TriangleObstacle = TriangleObstacle

@typing_extensions.final
class LineObstacle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    @property
    def start(self) -> global___Vector: ...
    @property
    def end(self) -> global___Vector: ...
    def __init__(
        self,
        *,
        start: global___Vector | None = ...,
        end: global___Vector | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end", b"end", "start", b"start"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["end", b"end", "start", b"start"]) -> None: ...

global___LineObstacle = LineObstacle

@typing_extensions.final
class MovingCircleObstacle(google.protobuf.message.Message):
    """moving obstacles"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_POS_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    ACC_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    @property
    def start_pos(self) -> global___Vector: ...
    @property
    def speed(self) -> global___Vector: ...
    @property
    def acc(self) -> global___Vector: ...
    start_time: builtins.float
    end_time: builtins.float
    def __init__(
        self,
        *,
        start_pos: global___Vector | None = ...,
        speed: global___Vector | None = ...,
        acc: global___Vector | None = ...,
        start_time: builtins.float | None = ...,
        end_time: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["acc", b"acc", "end_time", b"end_time", "speed", b"speed", "start_pos", b"start_pos", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["acc", b"acc", "end_time", b"end_time", "speed", b"speed", "start_pos", b"start_pos", "start_time", b"start_time"]) -> None: ...

global___MovingCircleObstacle = MovingCircleObstacle

@typing_extensions.final
class MovingLineObstacle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_POS1_FIELD_NUMBER: builtins.int
    SPEED1_FIELD_NUMBER: builtins.int
    ACC1_FIELD_NUMBER: builtins.int
    START_POS2_FIELD_NUMBER: builtins.int
    SPEED2_FIELD_NUMBER: builtins.int
    ACC2_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    @property
    def start_pos1(self) -> global___Vector: ...
    @property
    def speed1(self) -> global___Vector: ...
    @property
    def acc1(self) -> global___Vector: ...
    @property
    def start_pos2(self) -> global___Vector: ...
    @property
    def speed2(self) -> global___Vector: ...
    @property
    def acc2(self) -> global___Vector: ...
    start_time: builtins.float
    end_time: builtins.float
    def __init__(
        self,
        *,
        start_pos1: global___Vector | None = ...,
        speed1: global___Vector | None = ...,
        acc1: global___Vector | None = ...,
        start_pos2: global___Vector | None = ...,
        speed2: global___Vector | None = ...,
        acc2: global___Vector | None = ...,
        start_time: builtins.float | None = ...,
        end_time: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["acc1", b"acc1", "acc2", b"acc2", "end_time", b"end_time", "speed1", b"speed1", "speed2", b"speed2", "start_pos1", b"start_pos1", "start_pos2", b"start_pos2", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["acc1", b"acc1", "acc2", b"acc2", "end_time", b"end_time", "speed1", b"speed1", "speed2", b"speed2", "start_pos1", b"start_pos1", "start_pos2", b"start_pos2", "start_time", b"start_time"]) -> None: ...

global___MovingLineObstacle = MovingLineObstacle

@typing_extensions.final
class TrajectoryPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POS_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    @property
    def pos(self) -> global___Vector: ...
    @property
    def speed(self) -> global___Vector: ...
    time: builtins.float
    def __init__(
        self,
        *,
        pos: global___Vector | None = ...,
        speed: global___Vector | None = ...,
        time: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pos", b"pos", "speed", b"speed", "time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pos", b"pos", "speed", b"speed", "time", b"time"]) -> None: ...

global___TrajectoryPoint = TrajectoryPoint

@typing_extensions.final
class FriendlyRobotObstacle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROBOT_TRAJECTORY_FIELD_NUMBER: builtins.int
    @property
    def robot_trajectory(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TrajectoryPoint]: ...
    def __init__(
        self,
        *,
        robot_trajectory: collections.abc.Iterable[global___TrajectoryPoint] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["robot_trajectory", b"robot_trajectory"]) -> None: ...

global___FriendlyRobotObstacle = FriendlyRobotObstacle

@typing_extensions.final
class OpponentRobotObstacle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_POS_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    @property
    def start_pos(self) -> global___Vector: ...
    @property
    def speed(self) -> global___Vector: ...
    def __init__(
        self,
        *,
        start_pos: global___Vector | None = ...,
        speed: global___Vector | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["speed", b"speed", "start_pos", b"start_pos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["speed", b"speed", "start_pos", b"start_pos"]) -> None: ...

global___OpponentRobotObstacle = OpponentRobotObstacle

@typing_extensions.final
class Obstacle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PRIO_FIELD_NUMBER: builtins.int
    RADIUS_FIELD_NUMBER: builtins.int
    CIRCLE_FIELD_NUMBER: builtins.int
    RECTANGLE_FIELD_NUMBER: builtins.int
    TRIANGLE_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    MOVING_CIRCLE_FIELD_NUMBER: builtins.int
    MOVING_LINE_FIELD_NUMBER: builtins.int
    FRIENDLY_ROBOT_FIELD_NUMBER: builtins.int
    OPPONENT_ROBOT_FIELD_NUMBER: builtins.int
    name: builtins.str
    prio: builtins.int
    radius: builtins.float
    @property
    def circle(self) -> global___CircleObstacle: ...
    @property
    def rectangle(self) -> global___RectObstacle: ...
    @property
    def triangle(self) -> global___TriangleObstacle: ...
    @property
    def line(self) -> global___LineObstacle: ...
    @property
    def moving_circle(self) -> global___MovingCircleObstacle:
        """reserved: 8"""
    @property
    def moving_line(self) -> global___MovingLineObstacle: ...
    @property
    def friendly_robot(self) -> global___FriendlyRobotObstacle: ...
    @property
    def opponent_robot(self) -> global___OpponentRobotObstacle: ...
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        prio: builtins.int | None = ...,
        radius: builtins.float | None = ...,
        circle: global___CircleObstacle | None = ...,
        rectangle: global___RectObstacle | None = ...,
        triangle: global___TriangleObstacle | None = ...,
        line: global___LineObstacle | None = ...,
        moving_circle: global___MovingCircleObstacle | None = ...,
        moving_line: global___MovingLineObstacle | None = ...,
        friendly_robot: global___FriendlyRobotObstacle | None = ...,
        opponent_robot: global___OpponentRobotObstacle | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["circle", b"circle", "friendly_robot", b"friendly_robot", "line", b"line", "moving_circle", b"moving_circle", "moving_line", b"moving_line", "name", b"name", "obstacle", b"obstacle", "opponent_robot", b"opponent_robot", "prio", b"prio", "radius", b"radius", "rectangle", b"rectangle", "triangle", b"triangle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["circle", b"circle", "friendly_robot", b"friendly_robot", "line", b"line", "moving_circle", b"moving_circle", "moving_line", b"moving_line", "name", b"name", "obstacle", b"obstacle", "opponent_robot", b"opponent_robot", "prio", b"prio", "radius", b"radius", "rectangle", b"rectangle", "triangle", b"triangle"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["obstacle", b"obstacle"]) -> typing_extensions.Literal["circle", "rectangle", "triangle", "line", "moving_circle", "moving_line", "friendly_robot", "opponent_robot"] | None: ...

global___Obstacle = Obstacle

@typing_extensions.final
class WorldState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBSTACLES_FIELD_NUMBER: builtins.int
    OUT_OF_FIELD_PRIORITY_FIELD_NUMBER: builtins.int
    BOUNDARY_FIELD_NUMBER: builtins.int
    RADIUS_FIELD_NUMBER: builtins.int
    ROBOT_ID_FIELD_NUMBER: builtins.int
    @property
    def obstacles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Obstacle]: ...
    out_of_field_priority: builtins.int
    @property
    def boundary(self) -> global___RectObstacle: ...
    radius: builtins.float
    robot_id: builtins.int
    def __init__(
        self,
        *,
        obstacles: collections.abc.Iterable[global___Obstacle] | None = ...,
        out_of_field_priority: builtins.int | None = ...,
        boundary: global___RectObstacle | None = ...,
        radius: builtins.float | None = ...,
        robot_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["boundary", b"boundary", "out_of_field_priority", b"out_of_field_priority", "radius", b"radius", "robot_id", b"robot_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["boundary", b"boundary", "obstacles", b"obstacles", "out_of_field_priority", b"out_of_field_priority", "radius", b"radius", "robot_id", b"robot_id"]) -> None: ...

global___WorldState = WorldState

@typing_extensions.final
class TrajectoryInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    V0_FIELD_NUMBER: builtins.int
    V1_FIELD_NUMBER: builtins.int
    S0_FIELD_NUMBER: builtins.int
    S1_FIELD_NUMBER: builtins.int
    MAX_SPEED_FIELD_NUMBER: builtins.int
    ACCELERATION_FIELD_NUMBER: builtins.int
    @property
    def v0(self) -> global___Vector: ...
    @property
    def v1(self) -> global___Vector: ...
    @property
    def s0(self) -> global___Vector: ...
    @property
    def s1(self) -> global___Vector: ...
    max_speed: builtins.float
    acceleration: builtins.float
    def __init__(
        self,
        *,
        v0: global___Vector | None = ...,
        v1: global___Vector | None = ...,
        s0: global___Vector | None = ...,
        s1: global___Vector | None = ...,
        max_speed: builtins.float | None = ...,
        acceleration: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["acceleration", b"acceleration", "max_speed", b"max_speed", "s0", b"s0", "s1", b"s1", "v0", b"v0", "v1", b"v1"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["acceleration", b"acceleration", "max_speed", b"max_speed", "s0", b"s0", "s1", b"s1", "v0", b"v0", "v1", b"v1"]) -> None: ...

global___TrajectoryInput = TrajectoryInput

@typing_extensions.final
class PathFindingTask(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    INPUT_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def state(self) -> global___WorldState: ...
    @property
    def input(self) -> global___TrajectoryInput: ...
    type: global___InputSourceType.ValueType
    def __init__(
        self,
        *,
        state: global___WorldState | None = ...,
        input: global___TrajectoryInput | None = ...,
        type: global___InputSourceType.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["input", b"input", "state", b"state", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["input", b"input", "state", b"state", "type", b"type"]) -> None: ...

global___PathFindingTask = PathFindingTask

@typing_extensions.final
class StandardSamplerPoint(google.protobuf.message.Message):
    """these messages are for defining the pre-computed values to use during run-time"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIME_FIELD_NUMBER: builtins.int
    ANGLE_FIELD_NUMBER: builtins.int
    MID_SPEED_X_FIELD_NUMBER: builtins.int
    MID_SPEED_Y_FIELD_NUMBER: builtins.int
    time: builtins.float
    angle: builtins.float
    mid_speed_x: builtins.float
    mid_speed_y: builtins.float
    def __init__(
        self,
        *,
        time: builtins.float | None = ...,
        angle: builtins.float | None = ...,
        mid_speed_x: builtins.float | None = ...,
        mid_speed_y: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["angle", b"angle", "mid_speed_x", b"mid_speed_x", "mid_speed_y", b"mid_speed_y", "time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["angle", b"angle", "mid_speed_x", b"mid_speed_x", "mid_speed_y", b"mid_speed_y", "time", b"time"]) -> None: ...

global___StandardSamplerPoint = StandardSamplerPoint

@typing_extensions.final
class StandardSamplerPrecomputationSegment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRECOMPUTED_POINTS_FIELD_NUMBER: builtins.int
    MIN_DISTANCE_FIELD_NUMBER: builtins.int
    MAX_DISTANCE_FIELD_NUMBER: builtins.int
    @property
    def precomputed_points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StandardSamplerPoint]: ...
    min_distance: builtins.float
    max_distance: builtins.float
    def __init__(
        self,
        *,
        precomputed_points: collections.abc.Iterable[global___StandardSamplerPoint] | None = ...,
        min_distance: builtins.float | None = ...,
        max_distance: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["max_distance", b"max_distance", "min_distance", b"min_distance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["max_distance", b"max_distance", "min_distance", b"min_distance", "precomputed_points", b"precomputed_points"]) -> None: ...

global___StandardSamplerPrecomputationSegment = StandardSamplerPrecomputationSegment

@typing_extensions.final
class StandardSamplerPrecomputation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEGMENTS_FIELD_NUMBER: builtins.int
    @property
    def segments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StandardSamplerPrecomputationSegment]: ...
    def __init__(
        self,
        *,
        segments: collections.abc.Iterable[global___StandardSamplerPrecomputationSegment] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["segments", b"segments"]) -> None: ...

global___StandardSamplerPrecomputation = StandardSamplerPrecomputation
