"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class LimitParameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    A_SPEEDUP_F_MAX_FIELD_NUMBER: builtins.int
    A_SPEEDUP_S_MAX_FIELD_NUMBER: builtins.int
    A_SPEEDUP_PHI_MAX_FIELD_NUMBER: builtins.int
    A_BRAKE_F_MAX_FIELD_NUMBER: builtins.int
    A_BRAKE_S_MAX_FIELD_NUMBER: builtins.int
    A_BRAKE_PHI_MAX_FIELD_NUMBER: builtins.int
    a_speedup_f_max: builtins.float
    a_speedup_s_max: builtins.float
    a_speedup_phi_max: builtins.float
    a_brake_f_max: builtins.float
    a_brake_s_max: builtins.float
    a_brake_phi_max: builtins.float
    def __init__(
        self,
        *,
        a_speedup_f_max: builtins.float | None = ...,
        a_speedup_s_max: builtins.float | None = ...,
        a_speedup_phi_max: builtins.float | None = ...,
        a_brake_f_max: builtins.float | None = ...,
        a_brake_s_max: builtins.float | None = ...,
        a_brake_phi_max: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["a_brake_f_max", b"a_brake_f_max", "a_brake_phi_max", b"a_brake_phi_max", "a_brake_s_max", b"a_brake_s_max", "a_speedup_f_max", b"a_speedup_f_max", "a_speedup_phi_max", b"a_speedup_phi_max", "a_speedup_s_max", b"a_speedup_s_max"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["a_brake_f_max", b"a_brake_f_max", "a_brake_phi_max", b"a_brake_phi_max", "a_brake_s_max", b"a_brake_s_max", "a_speedup_f_max", b"a_speedup_f_max", "a_speedup_phi_max", b"a_speedup_phi_max", "a_speedup_s_max", b"a_speedup_s_max"]) -> None: ...

global___LimitParameters = LimitParameters

@typing_extensions.final
class SimulationLimits(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    A_SPEEDUP_WHEEL_MAX_FIELD_NUMBER: builtins.int
    A_BRAKE_WHEEL_MAX_FIELD_NUMBER: builtins.int
    a_speedup_wheel_max: builtins.float
    """in rotations per second^2"""
    a_brake_wheel_max: builtins.float
    def __init__(
        self,
        *,
        a_speedup_wheel_max: builtins.float | None = ...,
        a_brake_wheel_max: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["a_brake_wheel_max", b"a_brake_wheel_max", "a_speedup_wheel_max", b"a_speedup_wheel_max"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["a_brake_wheel_max", b"a_brake_wheel_max", "a_speedup_wheel_max", b"a_speedup_wheel_max"]) -> None: ...

global___SimulationLimits = SimulationLimits

@typing_extensions.final
class Specs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _GenerationType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _GenerationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Specs._GenerationType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Regular: Specs._GenerationType.ValueType  # 1
        Ally: Specs._GenerationType.ValueType  # 2

    class GenerationType(_GenerationType, metaclass=_GenerationTypeEnumTypeWrapper): ...
    Regular: Specs.GenerationType.ValueType  # 1
    Ally: Specs.GenerationType.ValueType  # 2

    GENERATION_FIELD_NUMBER: builtins.int
    YEAR_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    RADIUS_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    MASS_FIELD_NUMBER: builtins.int
    ANGLE_FIELD_NUMBER: builtins.int
    V_MAX_FIELD_NUMBER: builtins.int
    OMEGA_MAX_FIELD_NUMBER: builtins.int
    SHOT_LINEAR_MAX_FIELD_NUMBER: builtins.int
    SHOT_CHIP_MAX_FIELD_NUMBER: builtins.int
    DRIBBLER_WIDTH_FIELD_NUMBER: builtins.int
    ACCELERATION_FIELD_NUMBER: builtins.int
    STRATEGY_FIELD_NUMBER: builtins.int
    IR_PARAM_FIELD_NUMBER: builtins.int
    SHOOT_RADIUS_FIELD_NUMBER: builtins.int
    DRIBBLER_HEIGHT_FIELD_NUMBER: builtins.int
    SIMULATION_LIMITS_FIELD_NUMBER: builtins.int
    generation: builtins.int
    year: builtins.int
    id: builtins.int
    type: global___Specs.GenerationType.ValueType
    radius: builtins.float
    height: builtins.float
    mass: builtins.float
    angle: builtins.float
    v_max: builtins.float
    omega_max: builtins.float
    shot_linear_max: builtins.float
    shot_chip_max: builtins.float
    dribbler_width: builtins.float
    @property
    def acceleration(self) -> global___LimitParameters: ...
    @property
    def strategy(self) -> global___LimitParameters: ...
    ir_param: builtins.float
    """deprecated = 14;"""
    shoot_radius: builtins.float
    dribbler_height: builtins.float
    @property
    def simulation_limits(self) -> global___SimulationLimits:
        """if not present, the 'acceleration' field is used instread (with an additional acceleration factor)"""
    def __init__(
        self,
        *,
        generation: builtins.int | None = ...,
        year: builtins.int | None = ...,
        id: builtins.int | None = ...,
        type: global___Specs.GenerationType.ValueType | None = ...,
        radius: builtins.float | None = ...,
        height: builtins.float | None = ...,
        mass: builtins.float | None = ...,
        angle: builtins.float | None = ...,
        v_max: builtins.float | None = ...,
        omega_max: builtins.float | None = ...,
        shot_linear_max: builtins.float | None = ...,
        shot_chip_max: builtins.float | None = ...,
        dribbler_width: builtins.float | None = ...,
        acceleration: global___LimitParameters | None = ...,
        strategy: global___LimitParameters | None = ...,
        ir_param: builtins.float | None = ...,
        shoot_radius: builtins.float | None = ...,
        dribbler_height: builtins.float | None = ...,
        simulation_limits: global___SimulationLimits | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["acceleration", b"acceleration", "angle", b"angle", "dribbler_height", b"dribbler_height", "dribbler_width", b"dribbler_width", "generation", b"generation", "height", b"height", "id", b"id", "ir_param", b"ir_param", "mass", b"mass", "omega_max", b"omega_max", "radius", b"radius", "shoot_radius", b"shoot_radius", "shot_chip_max", b"shot_chip_max", "shot_linear_max", b"shot_linear_max", "simulation_limits", b"simulation_limits", "strategy", b"strategy", "type", b"type", "v_max", b"v_max", "year", b"year"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["acceleration", b"acceleration", "angle", b"angle", "dribbler_height", b"dribbler_height", "dribbler_width", b"dribbler_width", "generation", b"generation", "height", b"height", "id", b"id", "ir_param", b"ir_param", "mass", b"mass", "omega_max", b"omega_max", "radius", b"radius", "shoot_radius", b"shoot_radius", "shot_chip_max", b"shot_chip_max", "shot_linear_max", b"shot_linear_max", "simulation_limits", b"simulation_limits", "strategy", b"strategy", "type", b"type", "v_max", b"v_max", "year", b"year"]) -> None: ...

global___Specs = Specs

@typing_extensions.final
class Generation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULT_FIELD_NUMBER: builtins.int
    ROBOT_FIELD_NUMBER: builtins.int
    @property
    def default(self) -> global___Specs: ...
    @property
    def robot(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Specs]: ...
    def __init__(
        self,
        *,
        default: global___Specs | None = ...,
        robot: collections.abc.Iterable[global___Specs] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["default", b"default"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["default", b"default", "robot", b"robot"]) -> None: ...

global___Generation = Generation

@typing_extensions.final
class Team(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROBOT_FIELD_NUMBER: builtins.int
    @property
    def robot(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Specs]: ...
    def __init__(
        self,
        *,
        robot: collections.abc.Iterable[global___Specs] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["robot", b"robot"]) -> None: ...

global___Team = Team

@typing_extensions.final
class Polynomial(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    A0_FIELD_NUMBER: builtins.int
    A1_FIELD_NUMBER: builtins.int
    A2_FIELD_NUMBER: builtins.int
    A3_FIELD_NUMBER: builtins.int
    a0: builtins.float
    a1: builtins.float
    a2: builtins.float
    a3: builtins.float
    def __init__(
        self,
        *,
        a0: builtins.float | None = ...,
        a1: builtins.float | None = ...,
        a2: builtins.float | None = ...,
        a3: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["a0", b"a0", "a1", b"a1", "a2", b"a2", "a3", b"a3"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["a0", b"a0", "a1", b"a1", "a2", b"a2", "a3", b"a3"]) -> None: ...

global___Polynomial = Polynomial

@typing_extensions.final
class Spline(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    T_START_FIELD_NUMBER: builtins.int
    T_END_FIELD_NUMBER: builtins.int
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    PHI_FIELD_NUMBER: builtins.int
    t_start: builtins.float
    t_end: builtins.float
    @property
    def x(self) -> global___Polynomial: ...
    @property
    def y(self) -> global___Polynomial: ...
    @property
    def phi(self) -> global___Polynomial: ...
    def __init__(
        self,
        *,
        t_start: builtins.float | None = ...,
        t_end: builtins.float | None = ...,
        x: global___Polynomial | None = ...,
        y: global___Polynomial | None = ...,
        phi: global___Polynomial | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["phi", b"phi", "t_end", b"t_end", "t_start", b"t_start", "x", b"x", "y", b"y"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["phi", b"phi", "t_end", b"t_end", "t_start", b"t_start", "x", b"x", "y", b"y"]) -> None: ...

global___Spline = Spline

@typing_extensions.final
class ControllerInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPLINE_FIELD_NUMBER: builtins.int
    @property
    def spline(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Spline]: ...
    def __init__(
        self,
        *,
        spline: collections.abc.Iterable[global___Spline] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["spline", b"spline"]) -> None: ...

global___ControllerInput = ControllerInput

@typing_extensions.final
class SpeedVector(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    V_S_FIELD_NUMBER: builtins.int
    V_F_FIELD_NUMBER: builtins.int
    OMEGA_FIELD_NUMBER: builtins.int
    v_s: builtins.float
    v_f: builtins.float
    omega: builtins.float
    def __init__(
        self,
        *,
        v_s: builtins.float | None = ...,
        v_f: builtins.float | None = ...,
        omega: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["omega", b"omega", "v_f", b"v_f", "v_s", b"v_s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["omega", b"omega", "v_f", b"v_f", "v_s", b"v_s"]) -> None: ...

global___SpeedVector = SpeedVector

@typing_extensions.final
class Command(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _KickStyle:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _KickStyleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Command._KickStyle.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Linear: Command._KickStyle.ValueType  # 1
        Chip: Command._KickStyle.ValueType  # 2

    class KickStyle(_KickStyle, metaclass=_KickStyleEnumTypeWrapper): ...
    Linear: Command.KickStyle.ValueType  # 1
    Chip: Command.KickStyle.ValueType  # 2

    CONTROLLER_FIELD_NUMBER: builtins.int
    V_F_FIELD_NUMBER: builtins.int
    V_S_FIELD_NUMBER: builtins.int
    OMEGA_FIELD_NUMBER: builtins.int
    KICK_STYLE_FIELD_NUMBER: builtins.int
    KICK_POWER_FIELD_NUMBER: builtins.int
    DRIBBLER_FIELD_NUMBER: builtins.int
    LOCAL_FIELD_NUMBER: builtins.int
    STANDBY_FIELD_NUMBER: builtins.int
    STRATEGY_CONTROLLED_FIELD_NUMBER: builtins.int
    FORCE_KICK_FIELD_NUMBER: builtins.int
    NETWORK_CONTROLLED_FIELD_NUMBER: builtins.int
    EJECT_SDCARD_FIELD_NUMBER: builtins.int
    CUR_V_F_FIELD_NUMBER: builtins.int
    CUR_V_S_FIELD_NUMBER: builtins.int
    CUR_OMEGA_FIELD_NUMBER: builtins.int
    OUTPUT0_FIELD_NUMBER: builtins.int
    OUTPUT1_FIELD_NUMBER: builtins.int
    OUTPUT2_FIELD_NUMBER: builtins.int
    @property
    def controller(self) -> global___ControllerInput: ...
    v_f: builtins.float
    v_s: builtins.float
    omega: builtins.float
    kick_style: global___Command.KickStyle.ValueType
    kick_power: builtins.float
    dribbler: builtins.float
    local: builtins.bool
    standby: builtins.bool
    """deprecated = 9-10;"""
    strategy_controlled: builtins.bool
    """deprecated = 12"""
    force_kick: builtins.bool
    network_controlled: builtins.bool
    eject_sdcard: builtins.bool
    cur_v_f: builtins.float
    cur_v_s: builtins.float
    cur_omega: builtins.float
    @property
    def output0(self) -> global___SpeedVector: ...
    @property
    def output1(self) -> global___SpeedVector: ...
    @property
    def output2(self) -> global___SpeedVector: ...
    def __init__(
        self,
        *,
        controller: global___ControllerInput | None = ...,
        v_f: builtins.float | None = ...,
        v_s: builtins.float | None = ...,
        omega: builtins.float | None = ...,
        kick_style: global___Command.KickStyle.ValueType | None = ...,
        kick_power: builtins.float | None = ...,
        dribbler: builtins.float | None = ...,
        local: builtins.bool | None = ...,
        standby: builtins.bool | None = ...,
        strategy_controlled: builtins.bool | None = ...,
        force_kick: builtins.bool | None = ...,
        network_controlled: builtins.bool | None = ...,
        eject_sdcard: builtins.bool | None = ...,
        cur_v_f: builtins.float | None = ...,
        cur_v_s: builtins.float | None = ...,
        cur_omega: builtins.float | None = ...,
        output0: global___SpeedVector | None = ...,
        output1: global___SpeedVector | None = ...,
        output2: global___SpeedVector | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["controller", b"controller", "cur_omega", b"cur_omega", "cur_v_f", b"cur_v_f", "cur_v_s", b"cur_v_s", "dribbler", b"dribbler", "eject_sdcard", b"eject_sdcard", "force_kick", b"force_kick", "kick_power", b"kick_power", "kick_style", b"kick_style", "local", b"local", "network_controlled", b"network_controlled", "omega", b"omega", "output0", b"output0", "output1", b"output1", "output2", b"output2", "standby", b"standby", "strategy_controlled", b"strategy_controlled", "v_f", b"v_f", "v_s", b"v_s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["controller", b"controller", "cur_omega", b"cur_omega", "cur_v_f", b"cur_v_f", "cur_v_s", b"cur_v_s", "dribbler", b"dribbler", "eject_sdcard", b"eject_sdcard", "force_kick", b"force_kick", "kick_power", b"kick_power", "kick_style", b"kick_style", "local", b"local", "network_controlled", b"network_controlled", "omega", b"omega", "output0", b"output0", "output1", b"output1", "output2", b"output2", "standby", b"standby", "strategy_controlled", b"strategy_controlled", "v_f", b"v_f", "v_s", b"v_s"]) -> None: ...

global___Command = Command

@typing_extensions.final
class RadioCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GENERATION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    IS_BLUE_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    COMMAND_TIME_FIELD_NUMBER: builtins.int
    generation: builtins.int
    id: builtins.int
    is_blue: builtins.bool
    @property
    def command(self) -> global___Command: ...
    command_time: builtins.int
    def __init__(
        self,
        *,
        generation: builtins.int | None = ...,
        id: builtins.int | None = ...,
        is_blue: builtins.bool | None = ...,
        command: global___Command | None = ...,
        command_time: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["command", b"command", "command_time", b"command_time", "generation", b"generation", "id", b"id", "is_blue", b"is_blue"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["command", b"command", "command_time", b"command_time", "generation", b"generation", "id", b"id", "is_blue", b"is_blue"]) -> None: ...

global___RadioCommand = RadioCommand

@typing_extensions.final
class SpeedStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    V_F_FIELD_NUMBER: builtins.int
    V_S_FIELD_NUMBER: builtins.int
    OMEGA_FIELD_NUMBER: builtins.int
    v_f: builtins.float
    v_s: builtins.float
    omega: builtins.float
    def __init__(
        self,
        *,
        v_f: builtins.float | None = ...,
        v_s: builtins.float | None = ...,
        omega: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["omega", b"omega", "v_f", b"v_f", "v_s", b"v_s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["omega", b"omega", "v_f", b"v_f", "v_s", b"v_s"]) -> None: ...

global___SpeedStatus = SpeedStatus

@typing_extensions.final
class ExtendedError(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOTOR_1_ERROR_FIELD_NUMBER: builtins.int
    MOTOR_2_ERROR_FIELD_NUMBER: builtins.int
    MOTOR_3_ERROR_FIELD_NUMBER: builtins.int
    MOTOR_4_ERROR_FIELD_NUMBER: builtins.int
    DRIBBLER_ERROR_FIELD_NUMBER: builtins.int
    KICKER_ERROR_FIELD_NUMBER: builtins.int
    KICKER_BREAK_BEAM_ERROR_FIELD_NUMBER: builtins.int
    MOTOR_ENCODER_ERROR_FIELD_NUMBER: builtins.int
    MAIN_SENSOR_ERROR_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    motor_1_error: builtins.bool
    motor_2_error: builtins.bool
    motor_3_error: builtins.bool
    motor_4_error: builtins.bool
    dribbler_error: builtins.bool
    kicker_error: builtins.bool
    kicker_break_beam_error: builtins.bool
    """optional bool motor_overheated_error = 8;"""
    motor_encoder_error: builtins.bool
    main_sensor_error: builtins.bool
    temperature: builtins.int
    def __init__(
        self,
        *,
        motor_1_error: builtins.bool | None = ...,
        motor_2_error: builtins.bool | None = ...,
        motor_3_error: builtins.bool | None = ...,
        motor_4_error: builtins.bool | None = ...,
        dribbler_error: builtins.bool | None = ...,
        kicker_error: builtins.bool | None = ...,
        kicker_break_beam_error: builtins.bool | None = ...,
        motor_encoder_error: builtins.bool | None = ...,
        main_sensor_error: builtins.bool | None = ...,
        temperature: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dribbler_error", b"dribbler_error", "kicker_break_beam_error", b"kicker_break_beam_error", "kicker_error", b"kicker_error", "main_sensor_error", b"main_sensor_error", "motor_1_error", b"motor_1_error", "motor_2_error", b"motor_2_error", "motor_3_error", b"motor_3_error", "motor_4_error", b"motor_4_error", "motor_encoder_error", b"motor_encoder_error", "temperature", b"temperature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dribbler_error", b"dribbler_error", "kicker_break_beam_error", b"kicker_break_beam_error", "kicker_error", b"kicker_error", "main_sensor_error", b"main_sensor_error", "motor_1_error", b"motor_1_error", "motor_2_error", b"motor_2_error", "motor_3_error", b"motor_3_error", "motor_4_error", b"motor_4_error", "motor_encoder_error", b"motor_encoder_error", "temperature", b"temperature"]) -> None: ...

global___ExtendedError = ExtendedError

@typing_extensions.final
class RadioResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIME_FIELD_NUMBER: builtins.int
    GENERATION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    BATTERY_FIELD_NUMBER: builtins.int
    PACKET_LOSS_RX_FIELD_NUMBER: builtins.int
    PACKET_LOSS_TX_FIELD_NUMBER: builtins.int
    ESTIMATED_SPEED_FIELD_NUMBER: builtins.int
    BALL_DETECTED_FIELD_NUMBER: builtins.int
    CAP_CHARGED_FIELD_NUMBER: builtins.int
    ERROR_PRESENT_FIELD_NUMBER: builtins.int
    RADIO_RTT_FIELD_NUMBER: builtins.int
    EXTENDED_ERROR_FIELD_NUMBER: builtins.int
    IS_BLUE_FIELD_NUMBER: builtins.int
    time: builtins.int
    generation: builtins.int
    id: builtins.int
    battery: builtins.float
    packet_loss_rx: builtins.float
    packet_loss_tx: builtins.float
    @property
    def estimated_speed(self) -> global___SpeedStatus: ...
    ball_detected: builtins.bool
    cap_charged: builtins.bool
    error_present: builtins.bool
    radio_rtt: builtins.float
    @property
    def extended_error(self) -> global___ExtendedError: ...
    is_blue: builtins.bool
    def __init__(
        self,
        *,
        time: builtins.int | None = ...,
        generation: builtins.int | None = ...,
        id: builtins.int | None = ...,
        battery: builtins.float | None = ...,
        packet_loss_rx: builtins.float | None = ...,
        packet_loss_tx: builtins.float | None = ...,
        estimated_speed: global___SpeedStatus | None = ...,
        ball_detected: builtins.bool | None = ...,
        cap_charged: builtins.bool | None = ...,
        error_present: builtins.bool | None = ...,
        radio_rtt: builtins.float | None = ...,
        extended_error: global___ExtendedError | None = ...,
        is_blue: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ball_detected", b"ball_detected", "battery", b"battery", "cap_charged", b"cap_charged", "error_present", b"error_present", "estimated_speed", b"estimated_speed", "extended_error", b"extended_error", "generation", b"generation", "id", b"id", "is_blue", b"is_blue", "packet_loss_rx", b"packet_loss_rx", "packet_loss_tx", b"packet_loss_tx", "radio_rtt", b"radio_rtt", "time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ball_detected", b"ball_detected", "battery", b"battery", "cap_charged", b"cap_charged", "error_present", b"error_present", "estimated_speed", b"estimated_speed", "extended_error", b"extended_error", "generation", b"generation", "id", b"id", "is_blue", b"is_blue", "packet_loss_rx", b"packet_loss_rx", "packet_loss_tx", b"packet_loss_tx", "radio_rtt", b"radio_rtt", "time", b"time"]) -> None: ...

global___RadioResponse = RadioResponse
