"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import ssl_game_controller_common_pb2
import ssl_game_controller_geometry_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GcState(google.protobuf.message.Message):
    """The GC state contains settings and state independent of the match state"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class TeamStateEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___GcStateTeam: ...
        def __init__(
            self,
            *,
            key: builtins.str | None = ...,
            value: global___GcStateTeam | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    @typing_extensions.final
    class AutoRefStateEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___GcStateAutoRef: ...
        def __init__(
            self,
            *,
            key: builtins.str | None = ...,
            value: global___GcStateAutoRef | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    @typing_extensions.final
    class TrackerStateEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___GcStateTracker: ...
        def __init__(
            self,
            *,
            key: builtins.str | None = ...,
            value: global___GcStateTracker | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    TEAM_STATE_FIELD_NUMBER: builtins.int
    AUTO_REF_STATE_FIELD_NUMBER: builtins.int
    TRACKER_STATE_FIELD_NUMBER: builtins.int
    TRACKER_STATE_GC_FIELD_NUMBER: builtins.int
    READY_TO_CONTINUE_FIELD_NUMBER: builtins.int
    @property
    def team_state(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___GcStateTeam]:
        """The state of each team"""
    @property
    def auto_ref_state(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___GcStateAutoRef]:
        """the states of the auto referees"""
    @property
    def tracker_state(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___GcStateTracker]:
        """the states of the attached trackers"""
    @property
    def tracker_state_gc(self) -> global___GcStateTracker:
        """the state of the currently selected tracker"""
    ready_to_continue: builtins.bool
    """can the match be continued right now?"""
    def __init__(
        self,
        *,
        team_state: collections.abc.Mapping[builtins.str, global___GcStateTeam] | None = ...,
        auto_ref_state: collections.abc.Mapping[builtins.str, global___GcStateAutoRef] | None = ...,
        tracker_state: collections.abc.Mapping[builtins.str, global___GcStateTracker] | None = ...,
        tracker_state_gc: global___GcStateTracker | None = ...,
        ready_to_continue: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "ready_to_continue", b"ready_to_continue", "tracker_state_gc", b"tracker_state_gc"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "auto_ref_state",
            b"auto_ref_state",
            "ready_to_continue",
            b"ready_to_continue",
            "team_state",
            b"team_state",
            "tracker_state",
            b"tracker_state",
            "tracker_state_gc",
            b"tracker_state_gc",
        ],
    ) -> None: ...

global___GcState = GcState

@typing_extensions.final
class GcStateTeam(google.protobuf.message.Message):
    """The GC state for a singl eteam"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTED_FIELD_NUMBER: builtins.int
    CONNECTION_VERIFIED_FIELD_NUMBER: builtins.int
    REMOTE_CONTROL_CONNECTED_FIELD_NUMBER: builtins.int
    REMOTE_CONTROL_CONNECTION_VERIFIED_FIELD_NUMBER: builtins.int
    connected: builtins.bool
    """true: The team is connected"""
    connection_verified: builtins.bool
    """true: The team connected via TLS with a verified certificate"""
    remote_control_connected: builtins.bool
    """true: The remote control for the team is connected"""
    remote_control_connection_verified: builtins.bool
    """true: The remote control for the team connected via TLS with a verified certificate"""
    def __init__(
        self,
        *,
        connected: builtins.bool | None = ...,
        connection_verified: builtins.bool | None = ...,
        remote_control_connected: builtins.bool | None = ...,
        remote_control_connection_verified: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "connected",
            b"connected",
            "connection_verified",
            b"connection_verified",
            "remote_control_connected",
            b"remote_control_connected",
            "remote_control_connection_verified",
            b"remote_control_connection_verified",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "connected",
            b"connected",
            "connection_verified",
            b"connection_verified",
            "remote_control_connected",
            b"remote_control_connected",
            "remote_control_connection_verified",
            b"remote_control_connection_verified",
        ],
    ) -> None: ...

global___GcStateTeam = GcStateTeam

@typing_extensions.final
class GcStateAutoRef(google.protobuf.message.Message):
    """The GC state of an auto referee"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTION_VERIFIED_FIELD_NUMBER: builtins.int
    connection_verified: builtins.bool
    """true: The autoRef connected via TLS with a verified certificate"""
    def __init__(
        self,
        *,
        connection_verified: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["connection_verified", b"connection_verified"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["connection_verified", b"connection_verified"]
    ) -> None: ...

global___GcStateAutoRef = GcStateAutoRef

@typing_extensions.final
class GcStateTracker(google.protobuf.message.Message):
    """GC state of a tracker"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_NAME_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    BALL_FIELD_NUMBER: builtins.int
    ROBOTS_FIELD_NUMBER: builtins.int
    source_name: builtins.str
    """Name of the source"""
    uuid: builtins.str
    """UUID of the source"""
    @property
    def ball(self) -> global___Ball:
        """Current ball"""
    @property
    def robots(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Robot]:
        """Current robots"""
    def __init__(
        self,
        *,
        source_name: builtins.str | None = ...,
        uuid: builtins.str | None = ...,
        ball: global___Ball | None = ...,
        robots: collections.abc.Iterable[global___Robot] | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "ball", b"ball", "source_name", b"source_name", "uuid", b"uuid"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "ball", b"ball", "robots", b"robots", "source_name", b"source_name", "uuid", b"uuid"
        ],
    ) -> None: ...

global___GcStateTracker = GcStateTracker

@typing_extensions.final
class Ball(google.protobuf.message.Message):
    """The ball state"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POS_FIELD_NUMBER: builtins.int
    VEL_FIELD_NUMBER: builtins.int
    @property
    def pos(self) -> ssl_game_controller_geometry_pb2.Vector3:
        """ball position [m]"""
    @property
    def vel(self) -> ssl_game_controller_geometry_pb2.Vector3:
        """ball velocity [m/s]"""
    def __init__(
        self,
        *,
        pos: ssl_game_controller_geometry_pb2.Vector3 | None = ...,
        vel: ssl_game_controller_geometry_pb2.Vector3 | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["pos", b"pos", "vel", b"vel"]
    ) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pos", b"pos", "vel", b"vel"]) -> None: ...

global___Ball = Ball

@typing_extensions.final
class Robot(google.protobuf.message.Message):
    """The robot state"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    POS_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> ssl_game_controller_common_pb2.BotId:
        """robot id and team"""
    @property
    def pos(self) -> ssl_game_controller_geometry_pb2.Vector2:
        """robot position [m]"""
    def __init__(
        self,
        *,
        id: ssl_game_controller_common_pb2.BotId | None = ...,
        pos: ssl_game_controller_geometry_pb2.Vector2 | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["id", b"id", "pos", b"pos"]
    ) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "pos", b"pos"]) -> None: ...

global___Robot = Robot
