# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_gc_engine_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1assl_gc_engine_config.proto\x12\x0egameController"\x91\x04\n\x06\x43onfig\x12J\n\x13game_event_behavior\x18\x01 \x03(\x0b\x32-.gameController.Config.GameEventBehaviorEntry\x12\x44\n\x10\x61uto_ref_configs\x18\x02 \x03(\x0b\x32*.gameController.Config.AutoRefConfigsEntry\x12\x1d\n\x15\x61\x63tive_tracker_source\x18\x03 \x01(\t\x12\r\n\x05teams\x18\x04 \x03(\t\x1aY\n\x16GameEventBehaviorEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0e\x32\x1f.gameController.Config.Behavior:\x02\x38\x01\x1aT\n\x13\x41utoRefConfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.gameController.AutoRefConfig:\x02\x38\x01"\x95\x01\n\x08\x42\x65havior\x12\x14\n\x10\x42\x45HAVIOR_UNKNOWN\x10\x00\x12\x13\n\x0f\x42\x45HAVIOR_ACCEPT\x10\x01\x12\x1c\n\x18\x42\x45HAVIOR_ACCEPT_MAJORITY\x10\x02\x12\x19\n\x15\x42\x45HAVIOR_PROPOSE_ONLY\x10\x03\x12\x10\n\x0c\x42\x45HAVIOR_LOG\x10\x04\x12\x13\n\x0f\x42\x45HAVIOR_IGNORE\x10\x05"\xa2\x02\n\rAutoRefConfig\x12Q\n\x13game_event_behavior\x18\x01 \x03(\x0b\x32\x34.gameController.AutoRefConfig.GameEventBehaviorEntry\x1a`\n\x16GameEventBehaviorEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x35\n\x05value\x18\x02 \x01(\x0e\x32&.gameController.AutoRefConfig.Behavior:\x02\x38\x01"\\\n\x08\x42\x65havior\x12\x14\n\x10\x42\x45HAVIOR_UNKNOWN\x10\x00\x12\x13\n\x0f\x42\x45HAVIOR_ACCEPT\x10\x01\x12\x10\n\x0c\x42\x45HAVIOR_LOG\x10\x02\x12\x13\n\x0f\x42\x45HAVIOR_IGNORE\x10\x03'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ssl_gc_engine_config_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _CONFIG_GAMEEVENTBEHAVIORENTRY._options = None
    _CONFIG_GAMEEVENTBEHAVIORENTRY._serialized_options = b"8\001"
    _CONFIG_AUTOREFCONFIGSENTRY._options = None
    _CONFIG_AUTOREFCONFIGSENTRY._serialized_options = b"8\001"
    _AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY._options = None
    _AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY._serialized_options = b"8\001"
    _CONFIG._serialized_start = 47
    _CONFIG._serialized_end = 576
    _CONFIG_GAMEEVENTBEHAVIORENTRY._serialized_start = 249
    _CONFIG_GAMEEVENTBEHAVIORENTRY._serialized_end = 338
    _CONFIG_AUTOREFCONFIGSENTRY._serialized_start = 340
    _CONFIG_AUTOREFCONFIGSENTRY._serialized_end = 424
    _CONFIG_BEHAVIOR._serialized_start = 427
    _CONFIG_BEHAVIOR._serialized_end = 576
    _AUTOREFCONFIG._serialized_start = 579
    _AUTOREFCONFIG._serialized_end = 869
    _AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY._serialized_start = 679
    _AUTOREFCONFIG_GAMEEVENTBEHAVIORENTRY._serialized_end = 775
    _AUTOREFCONFIG_BEHAVIOR._serialized_start = 777
    _AUTOREFCONFIG_BEHAVIOR._serialized_end = 869
# @@protoc_insertion_point(module_scope)
