"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import ssl_gc_change_pb2
import ssl_gc_engine_config_pb2
import ssl_gc_engine_pb2
import ssl_gc_state_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Output(google.protobuf.message.Message):
    """Message format that is pushed from the GC to the client"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MATCH_STATE_FIELD_NUMBER: builtins.int
    GC_STATE_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    @property
    def match_state(self) -> ssl_gc_state_pb2.State:
        """The current match state"""
    @property
    def gc_state(self) -> ssl_gc_engine_pb2.GcState:
        """The current GC state"""
    @property
    def protocol(self) -> global___Protocol:
        """The protocol"""
    @property
    def config(self) -> ssl_gc_engine_config_pb2.Config:
        """The engine config"""
    def __init__(
        self,
        *,
        match_state: ssl_gc_state_pb2.State | None = ...,
        gc_state: ssl_gc_engine_pb2.GcState | None = ...,
        protocol: global___Protocol | None = ...,
        config: ssl_gc_engine_config_pb2.Config | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "config",
            b"config",
            "gc_state",
            b"gc_state",
            "match_state",
            b"match_state",
            "protocol",
            b"protocol",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "config",
            b"config",
            "gc_state",
            b"gc_state",
            "match_state",
            b"match_state",
            "protocol",
            b"protocol",
        ],
    ) -> None: ...

global___Output = Output

@typing_extensions.final
class Protocol(google.protobuf.message.Message):
    """The game protocol"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DELTA_FIELD_NUMBER: builtins.int
    ENTRY_FIELD_NUMBER: builtins.int
    delta: builtins.bool
    """Is this a delta only?
    Entries that were already sent are not sent again, because the protocol is immutable anyway.
    But if the game is reset, the whole protocol must be replaced. That's what this flag is for.
    """
    @property
    def entry(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProtocolEntry]:
        """The (delta) list of entries"""
    def __init__(
        self,
        *,
        delta: builtins.bool | None = ...,
        entry: collections.abc.Iterable[global___ProtocolEntry] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["delta", b"delta"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["delta", b"delta", "entry", b"entry"]
    ) -> None: ...

global___Protocol = Protocol

@typing_extensions.final
class ProtocolEntry(google.protobuf.message.Message):
    """A protocol entry of a change"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CHANGE_FIELD_NUMBER: builtins.int
    MATCH_TIME_ELAPSED_FIELD_NUMBER: builtins.int
    STAGE_TIME_ELAPSED_FIELD_NUMBER: builtins.int
    id: builtins.int
    """Id of the entry"""
    @property
    def change(self) -> ssl_gc_change_pb2.Change:
        """The change that was made"""
    @property
    def match_time_elapsed(self) -> google.protobuf.duration_pb2.Duration:
        """The match time elapsed when this change was made"""
    @property
    def stage_time_elapsed(self) -> google.protobuf.duration_pb2.Duration:
        """The stage time elapsed when this change was made"""
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        change: ssl_gc_change_pb2.Change | None = ...,
        match_time_elapsed: google.protobuf.duration_pb2.Duration | None = ...,
        stage_time_elapsed: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "change",
            b"change",
            "id",
            b"id",
            "match_time_elapsed",
            b"match_time_elapsed",
            "stage_time_elapsed",
            b"stage_time_elapsed",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "change",
            b"change",
            "id",
            b"id",
            "match_time_elapsed",
            b"match_time_elapsed",
            "stage_time_elapsed",
            b"stage_time_elapsed",
        ],
    ) -> None: ...

global___ProtocolEntry = ProtocolEntry

@typing_extensions.final
class Input(google.protobuf.message.Message):
    """Message format that can be send from the client to the GC"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANGE_FIELD_NUMBER: builtins.int
    RESET_MATCH_FIELD_NUMBER: builtins.int
    CONFIG_DELTA_FIELD_NUMBER: builtins.int
    @property
    def change(self) -> ssl_gc_change_pb2.Change:
        """A change to be enqueued into the GC engine"""
    reset_match: builtins.bool
    """Reset the match"""
    @property
    def config_delta(self) -> ssl_gc_engine_config_pb2.Config:
        """An updated config delta"""
    def __init__(
        self,
        *,
        change: ssl_gc_change_pb2.Change | None = ...,
        reset_match: builtins.bool | None = ...,
        config_delta: ssl_gc_engine_config_pb2.Config | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "change", b"change", "config_delta", b"config_delta", "reset_match", b"reset_match"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "change", b"change", "config_delta", b"config_delta", "reset_match", b"reset_match"
        ],
    ) -> None: ...

global___Input = Input
