"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import ssl_gc_api_pb2
import ssl_geometry_pb2
import ssl_referee_pb2
import ssl_vision_wrapper_tracked_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CiInput(google.protobuf.message.Message):
    """The input format to the GC"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    TRACKER_PACKET_FIELD_NUMBER: builtins.int
    API_INPUTS_FIELD_NUMBER: builtins.int
    GEOMETRY_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    """New unix timestamp in [ns] for the GC"""
    @property
    def tracker_packet(self) -> ssl_vision_wrapper_tracked_pb2.TrackerWrapperPacket:
        """New tracker packet with ball and robot data"""
    @property
    def api_inputs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ssl_gc_api_pb2.Input]:
        """(UI) API input"""
    @property
    def geometry(self) -> ssl_geometry_pb2.SSL_GeometryData:
        """Update geometry"""
    def __init__(
        self,
        *,
        timestamp: builtins.int | None = ...,
        tracker_packet: ssl_vision_wrapper_tracked_pb2.TrackerWrapperPacket | None = ...,
        api_inputs: collections.abc.Iterable[ssl_gc_api_pb2.Input] | None = ...,
        geometry: ssl_geometry_pb2.SSL_GeometryData | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "geometry", b"geometry", "timestamp", b"timestamp", "tracker_packet", b"tracker_packet"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "api_inputs",
            b"api_inputs",
            "geometry",
            b"geometry",
            "timestamp",
            b"timestamp",
            "tracker_packet",
            b"tracker_packet",
        ],
    ) -> None: ...

global___CiInput = CiInput

@typing_extensions.final
class CiOutput(google.protobuf.message.Message):
    """The output format of the GC response"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REFEREE_MSG_FIELD_NUMBER: builtins.int
    @property
    def referee_msg(self) -> ssl_referee_pb2.SSL_Referee:
        """Latest referee message"""
    def __init__(
        self,
        *,
        referee_msg: ssl_referee_pb2.SSL_Referee | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["referee_msg", b"referee_msg"]
    ) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["referee_msg", b"referee_msg"]) -> None: ...

global___CiOutput = CiOutput
