# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_game_controller_team.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_game_controller_common_pb2 as ssl__game__controller__common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1essl_game_controller_team.proto\x12\x0egameController\x1a ssl_game_controller_common.proto"S\n\x10TeamRegistration\x12\x11\n\tteam_name\x18\x01 \x02(\t\x12,\n\tsignature\x18\x02 \x01(\x0b\x32\x19.gameController.Signature"\xc8\x01\n\x10TeamToController\x12,\n\tsignature\x18\x01 \x01(\x0b\x32\x19.gameController.Signature\x12\x18\n\x0e\x64\x65sired_keeper\x18\x02 \x01(\x05H\x00\x12;\n\x10\x61\x64vantage_choice\x18\x03 \x01(\x0e\x32\x1f.gameController.AdvantageChoiceH\x00\x12\x18\n\x0esubstitute_bot\x18\x04 \x01(\x08H\x00\x12\x0e\n\x04ping\x18\x05 \x01(\x08H\x00\x42\x05\n\x03msg"\\\n\x10\x43ontrollerToTeam\x12;\n\x10\x63ontroller_reply\x18\x01 \x01(\x0b\x32\x1f.gameController.ControllerReplyH\x00\x42\x05\n\x03msgJ\x04\x08\x02\x10\x03*)\n\x0f\x41\x64vantageChoice\x12\x08\n\x04STOP\x10\x00\x12\x0c\n\x08\x43ONTINUE\x10\x01'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ssl_game_controller_team_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ADVANTAGECHOICE._serialized_start = 466
    _ADVANTAGECHOICE._serialized_end = 507
    _TEAMREGISTRATION._serialized_start = 84
    _TEAMREGISTRATION._serialized_end = 167
    _TEAMTOCONTROLLER._serialized_start = 170
    _TEAMTOCONTROLLER._serialized_end = 370
    _CONTROLLERTOTEAM._serialized_start = 372
    _CONTROLLERTOTEAM._serialized_end = 464
# @@protoc_insertion_point(module_scope)
