"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import ssl_game_controller_common_pb2
import ssl_game_event_2019_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class AutoRefRegistration(google.protobuf.message.Message):
    """AutoRefRegistration is the first message that a client must send to the controller to identify itself"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    """identifier is a unique name of the client"""
    @property
    def signature(self) -> ssl_game_controller_common_pb2.Signature:
        """signature can optionally be specified to enable secure communication"""
    def __init__(
        self,
        *,
        identifier: builtins.str | None = ...,
        signature: ssl_game_controller_common_pb2.Signature | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["identifier", b"identifier", "signature", b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["identifier", b"identifier", "signature", b"signature"]) -> None: ...

global___AutoRefRegistration = AutoRefRegistration

@typing_extensions.final
class AutoRefToController(google.protobuf.message.Message):
    """AutoRefToController is the wrapper message for all subsequent messages from the autoRef to the controller"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIGNATURE_FIELD_NUMBER: builtins.int
    GAME_EVENT_FIELD_NUMBER: builtins.int
    @property
    def signature(self) -> ssl_game_controller_common_pb2.Signature:
        """signature can optionally be specified to enable secure communication"""
    @property
    def game_event(self) -> ssl_game_event_2019_pb2.GameEvent:
        """game_event is an optional event that the autoRef detected during the game"""
    def __init__(
        self,
        *,
        signature: ssl_game_controller_common_pb2.Signature | None = ...,
        game_event: ssl_game_event_2019_pb2.GameEvent | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["game_event", b"game_event", "signature", b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["game_event", b"game_event", "signature", b"signature"]) -> None: ...

global___AutoRefToController = AutoRefToController

@typing_extensions.final
class ControllerToAutoRef(google.protobuf.message.Message):
    """ControllerToAutoRef is the wrapper message for all messages from controller to autoRef"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTROLLER_REPLY_FIELD_NUMBER: builtins.int
    @property
    def controller_reply(self) -> ssl_game_controller_common_pb2.ControllerReply:
        """a reply from the controller"""
    def __init__(
        self,
        *,
        controller_reply: ssl_game_controller_common_pb2.ControllerReply | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["controller_reply", b"controller_reply", "msg", b"msg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["controller_reply", b"controller_reply", "msg", b"msg"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["controller_reply"] | None: ...

global___ControllerToAutoRef = ControllerToAutoRef
