"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import ssl_detection_pb2
import ssl_geometry_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SSL_WrapperPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DETECTION_FIELD_NUMBER: builtins.int
    GEOMETRY_FIELD_NUMBER: builtins.int
    @property
    def detection(self) -> ssl_detection_pb2.SSL_DetectionFrame: ...
    @property
    def geometry(self) -> ssl_geometry_pb2.SSL_GeometryData: ...
    def __init__(
        self,
        *,
        detection: ssl_detection_pb2.SSL_DetectionFrame | None = ...,
        geometry: ssl_geometry_pb2.SSL_GeometryData | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["detection", b"detection", "geometry", b"geometry"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["detection", b"detection", "geometry", b"geometry"]
    ) -> None: ...

global___SSL_WrapperPacket = SSL_WrapperPacket
