"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RobotSpecErForce(google.protobuf.message.Message):
    """Custom robot specs for ER-Force simulator"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SHOOT_RADIUS_FIELD_NUMBER: builtins.int
    DRIBBLER_HEIGHT_FIELD_NUMBER: builtins.int
    DRIBBLER_WIDTH_FIELD_NUMBER: builtins.int
    shoot_radius: builtins.float
    """The distance [m] from the robot center to the ball, when the ball is as close as possible to the robot.
    The ball may be a little bit inside the roboter when looking from top, due to the dimensions of the dribbler.
    """
    dribbler_height: builtins.float
    """The height of the dribbling bar from the ground [m]"""
    dribbler_width: builtins.float
    """The width of the dribbler itself (where the ball can be controlled), without the mechanical frame [m]."""
    def __init__(
        self,
        *,
        shoot_radius: builtins.float | None = ...,
        dribbler_height: builtins.float | None = ...,
        dribbler_width: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dribbler_height", b"dribbler_height", "dribbler_width", b"dribbler_width", "shoot_radius", b"shoot_radius"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dribbler_height", b"dribbler_height", "dribbler_width", b"dribbler_width", "shoot_radius", b"shoot_radius"]) -> None: ...

global___RobotSpecErForce = RobotSpecErForce
