"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import ssl_game_controller_common_pb2
import ssl_geometry_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RobotLimits(google.protobuf.message.Message):
    """Movement limits for a robot"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACC_SPEEDUP_ABSOLUTE_MAX_FIELD_NUMBER: builtins.int
    ACC_SPEEDUP_ANGULAR_MAX_FIELD_NUMBER: builtins.int
    ACC_BRAKE_ABSOLUTE_MAX_FIELD_NUMBER: builtins.int
    ACC_BRAKE_ANGULAR_MAX_FIELD_NUMBER: builtins.int
    VEL_ABSOLUTE_MAX_FIELD_NUMBER: builtins.int
    VEL_ANGULAR_MAX_FIELD_NUMBER: builtins.int
    acc_speedup_absolute_max: builtins.float
    """Max absolute speed-up acceleration [m/s^2]"""
    acc_speedup_angular_max: builtins.float
    """Max angular speed-up acceleration [rad/s^2]"""
    acc_brake_absolute_max: builtins.float
    """Max absolute brake acceleration [m/s^2]"""
    acc_brake_angular_max: builtins.float
    """Max angular brake acceleration [rad/s^2]"""
    vel_absolute_max: builtins.float
    """Max absolute velocity [m/s]"""
    vel_angular_max: builtins.float
    """Max angular velocity [rad/s]"""
    def __init__(
        self,
        *,
        acc_speedup_absolute_max: builtins.float | None = ...,
        acc_speedup_angular_max: builtins.float | None = ...,
        acc_brake_absolute_max: builtins.float | None = ...,
        acc_brake_angular_max: builtins.float | None = ...,
        vel_absolute_max: builtins.float | None = ...,
        vel_angular_max: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["acc_brake_absolute_max", b"acc_brake_absolute_max", "acc_brake_angular_max", b"acc_brake_angular_max", "acc_speedup_absolute_max", b"acc_speedup_absolute_max", "acc_speedup_angular_max", b"acc_speedup_angular_max", "vel_absolute_max", b"vel_absolute_max", "vel_angular_max", b"vel_angular_max"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["acc_brake_absolute_max", b"acc_brake_absolute_max", "acc_brake_angular_max", b"acc_brake_angular_max", "acc_speedup_absolute_max", b"acc_speedup_absolute_max", "acc_speedup_angular_max", b"acc_speedup_angular_max", "vel_absolute_max", b"vel_absolute_max", "vel_angular_max", b"vel_angular_max"]) -> None: ...

global___RobotLimits = RobotLimits

@typing_extensions.final
class RobotWheelAngles(google.protobuf.message.Message):
    """Robot wheel angle configuration
    all angles are relative to looking forward,
    all wheels / angles are clockwise
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRONT_RIGHT_FIELD_NUMBER: builtins.int
    BACK_RIGHT_FIELD_NUMBER: builtins.int
    BACK_LEFT_FIELD_NUMBER: builtins.int
    FRONT_LEFT_FIELD_NUMBER: builtins.int
    front_right: builtins.float
    """Angle front right [rad]"""
    back_right: builtins.float
    """Angle back right [rad]"""
    back_left: builtins.float
    """Angle back left [rad]"""
    front_left: builtins.float
    """Angle front left [rad]"""
    def __init__(
        self,
        *,
        front_right: builtins.float | None = ...,
        back_right: builtins.float | None = ...,
        back_left: builtins.float | None = ...,
        front_left: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["back_left", b"back_left", "back_right", b"back_right", "front_left", b"front_left", "front_right", b"front_right"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["back_left", b"back_left", "back_right", b"back_right", "front_left", b"front_left", "front_right", b"front_right"]) -> None: ...

global___RobotWheelAngles = RobotWheelAngles

@typing_extensions.final
class RobotSpecs(google.protobuf.message.Message):
    """Specs of a robot"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    RADIUS_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    MASS_FIELD_NUMBER: builtins.int
    MAX_LINEAR_KICK_SPEED_FIELD_NUMBER: builtins.int
    MAX_CHIP_KICK_SPEED_FIELD_NUMBER: builtins.int
    CENTER_TO_DRIBBLER_FIELD_NUMBER: builtins.int
    LIMITS_FIELD_NUMBER: builtins.int
    WHEEL_ANGLES_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> ssl_game_controller_common_pb2.BotId:
        """Id of the robot"""
    radius: builtins.float
    """Robot radius [m]"""
    height: builtins.float
    """Robot height [m]"""
    mass: builtins.float
    """Robot mass [kg]"""
    max_linear_kick_speed: builtins.float
    """Max linear kick speed [m/s] (unset = unlimited)"""
    max_chip_kick_speed: builtins.float
    """Max chip kick speed [m/s] (unset = unlimited)"""
    center_to_dribbler: builtins.float
    """Distance from robot center to dribbler [m] (implicitly defines the opening angle and dribbler width)"""
    @property
    def limits(self) -> global___RobotLimits:
        """Movement limits"""
    @property
    def wheel_angles(self) -> global___RobotWheelAngles:
        """Wheel angle configuration"""
    @property
    def custom(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]:
        """Custom robot spec for specific simulators (the protobuf files are managed by the simulators)"""
    def __init__(
        self,
        *,
        id: ssl_game_controller_common_pb2.BotId | None = ...,
        radius: builtins.float | None = ...,
        height: builtins.float | None = ...,
        mass: builtins.float | None = ...,
        max_linear_kick_speed: builtins.float | None = ...,
        max_chip_kick_speed: builtins.float | None = ...,
        center_to_dribbler: builtins.float | None = ...,
        limits: global___RobotLimits | None = ...,
        wheel_angles: global___RobotWheelAngles | None = ...,
        custom: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["center_to_dribbler", b"center_to_dribbler", "height", b"height", "id", b"id", "limits", b"limits", "mass", b"mass", "max_chip_kick_speed", b"max_chip_kick_speed", "max_linear_kick_speed", b"max_linear_kick_speed", "radius", b"radius", "wheel_angles", b"wheel_angles"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["center_to_dribbler", b"center_to_dribbler", "custom", b"custom", "height", b"height", "id", b"id", "limits", b"limits", "mass", b"mass", "max_chip_kick_speed", b"max_chip_kick_speed", "max_linear_kick_speed", b"max_linear_kick_speed", "radius", b"radius", "wheel_angles", b"wheel_angles"]) -> None: ...

global___RobotSpecs = RobotSpecs

@typing_extensions.final
class RealismConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CUSTOM_FIELD_NUMBER: builtins.int
    @property
    def custom(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]:
        """Custom config for specific simulators (the protobuf files are managed by the simulators)"""
    def __init__(
        self,
        *,
        custom: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["custom", b"custom"]) -> None: ...

global___RealismConfig = RealismConfig

@typing_extensions.final
class SimulatorConfig(google.protobuf.message.Message):
    """Change the simulator configuration"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GEOMETRY_FIELD_NUMBER: builtins.int
    ROBOT_SPECS_FIELD_NUMBER: builtins.int
    REALISM_CONFIG_FIELD_NUMBER: builtins.int
    VISION_PORT_FIELD_NUMBER: builtins.int
    @property
    def geometry(self) -> ssl_geometry_pb2.SSL_GeometryData:
        """Update the geometry"""
    @property
    def robot_specs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RobotSpecs]:
        """Update the robot specs"""
    @property
    def realism_config(self) -> global___RealismConfig:
        """Update realism configuration"""
    vision_port: builtins.int
    """Change the vision publish port"""
    def __init__(
        self,
        *,
        geometry: ssl_geometry_pb2.SSL_GeometryData | None = ...,
        robot_specs: collections.abc.Iterable[global___RobotSpecs] | None = ...,
        realism_config: global___RealismConfig | None = ...,
        vision_port: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["geometry", b"geometry", "realism_config", b"realism_config", "vision_port", b"vision_port"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["geometry", b"geometry", "realism_config", b"realism_config", "robot_specs", b"robot_specs", "vision_port", b"vision_port"]) -> None: ...

global___SimulatorConfig = SimulatorConfig
