"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import ssl_game_controller_common_pb2
import ssl_game_controller_geometry_pb2
import ssl_game_event_2019_pb2
import ssl_referee_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class YellowCard(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CAUSED_BY_GAME_EVENT_FIELD_NUMBER: builtins.int
    TIME_REMAINING_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def caused_by_game_event(self) -> ssl_game_event_2019_pb2.GameEvent: ...
    @property
    def time_remaining(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        caused_by_game_event: ssl_game_event_2019_pb2.GameEvent | None = ...,
        time_remaining: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "caused_by_game_event", b"caused_by_game_event", "id", b"id", "time_remaining", b"time_remaining"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "caused_by_game_event", b"caused_by_game_event", "id", b"id", "time_remaining", b"time_remaining"
        ],
    ) -> None: ...

global___YellowCard = YellowCard

@typing_extensions.final
class RedCard(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CAUSED_BY_GAME_EVENT_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def caused_by_game_event(self) -> ssl_game_event_2019_pb2.GameEvent: ...
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        caused_by_game_event: ssl_game_event_2019_pb2.GameEvent | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal["caused_by_game_event", b"caused_by_game_event", "id", b"id"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal["caused_by_game_event", b"caused_by_game_event", "id", b"id"],
    ) -> None: ...

global___RedCard = RedCard

@typing_extensions.final
class Foul(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CAUSED_BY_GAME_EVENT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def caused_by_game_event(self) -> ssl_game_event_2019_pb2.GameEvent: ...
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
        caused_by_game_event: ssl_game_event_2019_pb2.GameEvent | None = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "caused_by_game_event", b"caused_by_game_event", "id", b"id", "timestamp", b"timestamp"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "caused_by_game_event", b"caused_by_game_event", "id", b"id", "timestamp", b"timestamp"
        ],
    ) -> None: ...

global___Foul = Foul

@typing_extensions.final
class Command(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Command._Type.ValueType], builtins.type
    ):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Command._Type.ValueType  # 0
        HALT: Command._Type.ValueType  # 1
        STOP: Command._Type.ValueType  # 2
        NORMAL_START: Command._Type.ValueType  # 3
        FORCE_START: Command._Type.ValueType  # 4
        DIRECT: Command._Type.ValueType  # 5
        INDIRECT: Command._Type.ValueType  # 6
        KICKOFF: Command._Type.ValueType  # 7
        PENALTY: Command._Type.ValueType  # 8
        TIMEOUT: Command._Type.ValueType  # 9
        BALL_PLACEMENT: Command._Type.ValueType  # 10

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    UNKNOWN: Command.Type.ValueType  # 0
    HALT: Command.Type.ValueType  # 1
    STOP: Command.Type.ValueType  # 2
    NORMAL_START: Command.Type.ValueType  # 3
    FORCE_START: Command.Type.ValueType  # 4
    DIRECT: Command.Type.ValueType  # 5
    INDIRECT: Command.Type.ValueType  # 6
    KICKOFF: Command.Type.ValueType  # 7
    PENALTY: Command.Type.ValueType  # 8
    TIMEOUT: Command.Type.ValueType  # 9
    BALL_PLACEMENT: Command.Type.ValueType  # 10

    TYPE_FIELD_NUMBER: builtins.int
    FOR_TEAM_FIELD_NUMBER: builtins.int
    type: global___Command.Type.ValueType
    for_team: ssl_game_controller_common_pb2.Team.ValueType
    def __init__(
        self,
        *,
        type: global___Command.Type.ValueType | None = ...,
        for_team: ssl_game_controller_common_pb2.Team.ValueType | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["for_team", b"for_team", "type", b"type"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["for_team", b"for_team", "type", b"type"]
    ) -> None: ...

global___Command = Command

@typing_extensions.final
class GameState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[GameState._Type.ValueType], builtins.type
    ):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: GameState._Type.ValueType  # 0
        HALT: GameState._Type.ValueType  # 1
        STOP: GameState._Type.ValueType  # 2
        RUNNING: GameState._Type.ValueType  # 3
        FREE_KICK: GameState._Type.ValueType  # 4
        KICKOFF: GameState._Type.ValueType  # 5
        PENALTY: GameState._Type.ValueType  # 6
        TIMEOUT: GameState._Type.ValueType  # 7
        BALL_PLACEMENT: GameState._Type.ValueType  # 8

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    UNKNOWN: GameState.Type.ValueType  # 0
    HALT: GameState.Type.ValueType  # 1
    STOP: GameState.Type.ValueType  # 2
    RUNNING: GameState.Type.ValueType  # 3
    FREE_KICK: GameState.Type.ValueType  # 4
    KICKOFF: GameState.Type.ValueType  # 5
    PENALTY: GameState.Type.ValueType  # 6
    TIMEOUT: GameState.Type.ValueType  # 7
    BALL_PLACEMENT: GameState.Type.ValueType  # 8

    TYPE_FIELD_NUMBER: builtins.int
    FOR_TEAM_FIELD_NUMBER: builtins.int
    type: global___GameState.Type.ValueType
    for_team: ssl_game_controller_common_pb2.Team.ValueType
    def __init__(
        self,
        *,
        type: global___GameState.Type.ValueType | None = ...,
        for_team: ssl_game_controller_common_pb2.Team.ValueType | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["for_team", b"for_team", "type", b"type"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["for_team", b"for_team", "type", b"type"]
    ) -> None: ...

global___GameState = GameState

@typing_extensions.final
class Proposal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    GAME_EVENT_FIELD_NUMBER: builtins.int
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The timestamp when the game event proposal occurred"""
    @property
    def game_event(self) -> ssl_game_event_2019_pb2.GameEvent:
        """The proposed game event."""
    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        game_event: ssl_game_event_2019_pb2.GameEvent | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["game_event", b"game_event", "timestamp", b"timestamp"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["game_event", b"game_event", "timestamp", b"timestamp"]
    ) -> None: ...

global___Proposal = Proposal

@typing_extensions.final
class ProposalGroup(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROPOSALS_FIELD_NUMBER: builtins.int
    ACCEPTED_FIELD_NUMBER: builtins.int
    @property
    def proposals(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Proposal]:
        """List of proposals in this group"""
    accepted: builtins.bool
    """Whether the proposal group was accepted"""
    def __init__(
        self,
        *,
        proposals: collections.abc.Iterable[global___Proposal] | None = ...,
        accepted: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["accepted", b"accepted"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["accepted", b"accepted", "proposals", b"proposals"]
    ) -> None: ...

global___ProposalGroup = ProposalGroup

@typing_extensions.final
class TeamInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    GOALS_FIELD_NUMBER: builtins.int
    GOALKEEPER_FIELD_NUMBER: builtins.int
    YELLOW_CARDS_FIELD_NUMBER: builtins.int
    RED_CARDS_FIELD_NUMBER: builtins.int
    TIMEOUTS_LEFT_FIELD_NUMBER: builtins.int
    TIMEOUT_TIME_LEFT_FIELD_NUMBER: builtins.int
    ON_POSITIVE_HALF_FIELD_NUMBER: builtins.int
    FOULS_FIELD_NUMBER: builtins.int
    BALL_PLACEMENT_FAILURES_FIELD_NUMBER: builtins.int
    BALL_PLACEMENT_FAILURES_REACHED_FIELD_NUMBER: builtins.int
    CAN_PLACE_BALL_FIELD_NUMBER: builtins.int
    MAX_ALLOWED_BOTS_FIELD_NUMBER: builtins.int
    REQUESTS_BOT_SUBSTITUTION_SINCE_FIELD_NUMBER: builtins.int
    REQUESTS_TIMEOUT_SINCE_FIELD_NUMBER: builtins.int
    REQUESTS_EMERGENCY_STOP_SINCE_FIELD_NUMBER: builtins.int
    CHALLENGE_FLAGS_FIELD_NUMBER: builtins.int
    name: builtins.str
    goals: builtins.int
    goalkeeper: builtins.int
    @property
    def yellow_cards(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___YellowCard]: ...
    @property
    def red_cards(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RedCard]: ...
    timeouts_left: builtins.int
    @property
    def timeout_time_left(self) -> google.protobuf.duration_pb2.Duration: ...
    on_positive_half: builtins.bool
    @property
    def fouls(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Foul]: ...
    ball_placement_failures: builtins.int
    ball_placement_failures_reached: builtins.bool
    can_place_ball: builtins.bool
    max_allowed_bots: builtins.int
    @property
    def requests_bot_substitution_since(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def requests_timeout_since(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def requests_emergency_stop_since(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    challenge_flags: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        goals: builtins.int | None = ...,
        goalkeeper: builtins.int | None = ...,
        yellow_cards: collections.abc.Iterable[global___YellowCard] | None = ...,
        red_cards: collections.abc.Iterable[global___RedCard] | None = ...,
        timeouts_left: builtins.int | None = ...,
        timeout_time_left: google.protobuf.duration_pb2.Duration | None = ...,
        on_positive_half: builtins.bool | None = ...,
        fouls: collections.abc.Iterable[global___Foul] | None = ...,
        ball_placement_failures: builtins.int | None = ...,
        ball_placement_failures_reached: builtins.bool | None = ...,
        can_place_ball: builtins.bool | None = ...,
        max_allowed_bots: builtins.int | None = ...,
        requests_bot_substitution_since: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        requests_timeout_since: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        requests_emergency_stop_since: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        challenge_flags: builtins.int | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "ball_placement_failures",
            b"ball_placement_failures",
            "ball_placement_failures_reached",
            b"ball_placement_failures_reached",
            "can_place_ball",
            b"can_place_ball",
            "challenge_flags",
            b"challenge_flags",
            "goalkeeper",
            b"goalkeeper",
            "goals",
            b"goals",
            "max_allowed_bots",
            b"max_allowed_bots",
            "name",
            b"name",
            "on_positive_half",
            b"on_positive_half",
            "requests_bot_substitution_since",
            b"requests_bot_substitution_since",
            "requests_emergency_stop_since",
            b"requests_emergency_stop_since",
            "requests_timeout_since",
            b"requests_timeout_since",
            "timeout_time_left",
            b"timeout_time_left",
            "timeouts_left",
            b"timeouts_left",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "ball_placement_failures",
            b"ball_placement_failures",
            "ball_placement_failures_reached",
            b"ball_placement_failures_reached",
            "can_place_ball",
            b"can_place_ball",
            "challenge_flags",
            b"challenge_flags",
            "fouls",
            b"fouls",
            "goalkeeper",
            b"goalkeeper",
            "goals",
            b"goals",
            "max_allowed_bots",
            b"max_allowed_bots",
            "name",
            b"name",
            "on_positive_half",
            b"on_positive_half",
            "red_cards",
            b"red_cards",
            "requests_bot_substitution_since",
            b"requests_bot_substitution_since",
            "requests_emergency_stop_since",
            b"requests_emergency_stop_since",
            "requests_timeout_since",
            b"requests_timeout_since",
            "timeout_time_left",
            b"timeout_time_left",
            "timeouts_left",
            b"timeouts_left",
            "yellow_cards",
            b"yellow_cards",
        ],
    ) -> None: ...

global___TeamInfo = TeamInfo

@typing_extensions.final
class State(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class TeamStateEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___TeamInfo: ...
        def __init__(
            self,
            *,
            key: builtins.str | None = ...,
            value: global___TeamInfo | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    STAGE_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    GAME_STATE_FIELD_NUMBER: builtins.int
    STAGE_TIME_ELAPSED_FIELD_NUMBER: builtins.int
    STAGE_TIME_LEFT_FIELD_NUMBER: builtins.int
    MATCH_TIME_START_FIELD_NUMBER: builtins.int
    TEAM_STATE_FIELD_NUMBER: builtins.int
    PLACEMENT_POS_FIELD_NUMBER: builtins.int
    NEXT_COMMAND_FIELD_NUMBER: builtins.int
    CURRENT_ACTION_TIME_REMAINING_FIELD_NUMBER: builtins.int
    GAME_EVENTS_FIELD_NUMBER: builtins.int
    PROPOSAL_GROUPS_FIELD_NUMBER: builtins.int
    DIVISION_FIELD_NUMBER: builtins.int
    AUTO_CONTINUE_FIELD_NUMBER: builtins.int
    FIRST_KICKOFF_TEAM_FIELD_NUMBER: builtins.int
    stage: ssl_referee_pb2.SSL_Referee.Stage.ValueType
    @property
    def command(self) -> global___Command: ...
    @property
    def game_state(self) -> global___GameState: ...
    @property
    def stage_time_elapsed(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def stage_time_left(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def match_time_start(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def team_state(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___TeamInfo]: ...
    @property
    def placement_pos(self) -> ssl_game_controller_geometry_pb2.Vector2: ...
    @property
    def next_command(self) -> global___Command: ...
    @property
    def current_action_time_remaining(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def game_events(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        ssl_game_event_2019_pb2.GameEvent
    ]: ...
    @property
    def proposal_groups(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProposalGroup]: ...
    division: ssl_game_controller_common_pb2.Division.ValueType
    auto_continue: builtins.bool
    first_kickoff_team: ssl_game_controller_common_pb2.Team.ValueType
    def __init__(
        self,
        *,
        stage: ssl_referee_pb2.SSL_Referee.Stage.ValueType | None = ...,
        command: global___Command | None = ...,
        game_state: global___GameState | None = ...,
        stage_time_elapsed: google.protobuf.duration_pb2.Duration | None = ...,
        stage_time_left: google.protobuf.duration_pb2.Duration | None = ...,
        match_time_start: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        team_state: collections.abc.Mapping[builtins.str, global___TeamInfo] | None = ...,
        placement_pos: ssl_game_controller_geometry_pb2.Vector2 | None = ...,
        next_command: global___Command | None = ...,
        current_action_time_remaining: google.protobuf.duration_pb2.Duration | None = ...,
        game_events: collections.abc.Iterable[ssl_game_event_2019_pb2.GameEvent] | None = ...,
        proposal_groups: collections.abc.Iterable[global___ProposalGroup] | None = ...,
        division: ssl_game_controller_common_pb2.Division.ValueType | None = ...,
        auto_continue: builtins.bool | None = ...,
        first_kickoff_team: ssl_game_controller_common_pb2.Team.ValueType | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "auto_continue",
            b"auto_continue",
            "command",
            b"command",
            "current_action_time_remaining",
            b"current_action_time_remaining",
            "division",
            b"division",
            "first_kickoff_team",
            b"first_kickoff_team",
            "game_state",
            b"game_state",
            "match_time_start",
            b"match_time_start",
            "next_command",
            b"next_command",
            "placement_pos",
            b"placement_pos",
            "stage",
            b"stage",
            "stage_time_elapsed",
            b"stage_time_elapsed",
            "stage_time_left",
            b"stage_time_left",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "auto_continue",
            b"auto_continue",
            "command",
            b"command",
            "current_action_time_remaining",
            b"current_action_time_remaining",
            "division",
            b"division",
            "first_kickoff_team",
            b"first_kickoff_team",
            "game_events",
            b"game_events",
            "game_state",
            b"game_state",
            "match_time_start",
            b"match_time_start",
            "next_command",
            b"next_command",
            "placement_pos",
            b"placement_pos",
            "proposal_groups",
            b"proposal_groups",
            "stage",
            b"stage",
            "stage_time_elapsed",
            b"stage_time_elapsed",
            "stage_time_left",
            b"stage_time_left",
            "team_state",
            b"team_state",
        ],
    ) -> None: ...

global___State = State
