"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import command_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import robot_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class UserInput(google.protobuf.message.Message):
    """for strategy"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RADIO_COMMAND_FIELD_NUMBER: builtins.int
    MOVE_COMMAND_FIELD_NUMBER: builtins.int
    @property
    def radio_command(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[robot_pb2.RadioCommand]: ...
    @property
    def move_command(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        command_pb2.RobotMoveCommand
    ]: ...
    def __init__(
        self,
        *,
        radio_command: collections.abc.Iterable[robot_pb2.RadioCommand] | None = ...,
        move_command: collections.abc.Iterable[command_pb2.RobotMoveCommand] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "move_command", b"move_command", "radio_command", b"radio_command"
        ],
    ) -> None: ...

global___UserInput = UserInput
